import type { Metadata } from "next"
import "./globals.css"
import { ConvexClientProvider } from "@/providers/convex-provider"
import { QueryProvider } from "@/providers/query-provider"

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create-next-template",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>
        <QueryProvider>
        {children}
      </QueryProvider>
      </ConvexClientProvider>
      </body>
    </html>
  );
}
