import {
  si1password,
  siAnthropic,
  siApple,
  siApplearcade,
  siApplemusic,
  siApplenews,
  siApplepodcasts,
  siAppletv,
  siAsana,
  siAtlassian,
  siAudible,
  siBereal,
  siBitbucket,
  siBitwarden,
  siBlender,
  siBluesky,
  siCastro,
  siCloudflare,
  siConfluence,
  siCursor,
  siDashlane,
  siDeezer,
  siDigitalocean,
  siDiscord,
  siDropbox,
  siDuolingo,
  siExpressvpn,
  siFacebook,
  siFigma,
  siGithub,
  siGitlab,
  siGoogle,
  siGooglecloud,
  siGoogledrive,
  siGooglegemini,
  siHeadspace,
  siHbo,
  siHbomax,
  siInstagram,
  siJira,
  siLastpass,
  siLinear,
  siMastodon,
  siMedium,
  siMongodb,
  siNewyorktimes,
  siNetflix,
  siNetlify,
  siNordvpn,
  siNotion,
  siObsidian,
  siOvercast,
  siPatreon,
  siPeloton,
  siPinterest,
  siPlaystation,
  siPocketcasts,
  siProton,
  siProtondrive,
  siProtonmail,
  siProtonvpn,
  siRailway,
  siRaycast,
  siRender,
  siShopify,
  siSnapchat,
  siSoundcloud,
  siSpotify,
  siStripe,
  siSubstack,
  siSupabase,
  siThreads,
  siTidal,
  siTiktok,
  siTodoist,
  siTrello,
  siTwitch,
  siVercel,
  siYoutube,
  siYoutubemusic,
  siYoutubetv,
  siZoom,
} from "simple-icons";

type IconData = { path: string; hex: string };

function normalize(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

const ICON_MAP: Record<string, IconData> = {
  // Streaming
  netflix: siNetflix,
  spotify: siSpotify,
  youtube: siYoutube,
  youtubepremium: siYoutube,
  ytpremium: siYoutube,
  youtubemusic: siYoutubemusic,
  ytmusic: siYoutubemusic,
  youtubetv: siYoutubetv,
  hbo: siHbo,
  hbomax: siHbomax,
  max: siHbomax,
  // Apple
  apple: siApple,
  icloud: siApple,
  appleicloud: siApple,
  appletv: siAppletv,
  appletvplus: siAppletv,
  applemusic: siApplemusic,
  applearcade: siApplearcade,
  applenews: siApplenews,
  applenewsplus: siApplenews,
  applepodcasts: siApplepodcasts,
  // Google
  google: siGoogle,
  googleone: siGoogle,
  googledrive: siGoogledrive,
  googlecloud: siGooglecloud,
  gcp: siGooglecloud,
  gemini: siGooglegemini,
  googlegemini: siGooglegemini,
  // Dev tools
  github: siGithub,
  githubpro: siGithub,
  githubcopilot: siGithub,
  copilot: siGithub,
  gitlab: siGitlab,
  vercel: siVercel,
  netlify: siNetlify,
  cloudflare: siCloudflare,
  digitalocean: siDigitalocean,
  supabase: siSupabase,
  mongodb: siMongodb,
  mongo: siMongodb,
  railway: siRailway,
  render: siRender,
  bitbucket: siBitbucket,
  // Atlassian suite
  atlassian: siAtlassian,
  jira: siJira,
  confluence: siConfluence,
  trello: siTrello,
  // Productivity
  notion: siNotion,
  figma: siFigma,
  linear: siLinear,
  zoom: siZoom,
  cursor: siCursor,
  raycast: siRaycast,
  dropbox: siDropbox,
  obsidian: siObsidian,
  todoist: siTodoist,
  asana: siAsana,
  blender: siBlender,
  // AI
  claude: siAnthropic,
  anthropic: siAnthropic,
  // Social / Community
  discord: siDiscord,
  discordnitro: siDiscord,
  twitch: siTwitch,
  patreon: siPatreon,
  substack: siSubstack,
  medium: siMedium,
  instagram: siInstagram,
  facebook: siFacebook,
  snapchat: siSnapchat,
  tiktok: siTiktok,
  pinterest: siPinterest,
  threads: siThreads,
  bluesky: siBluesky,
  mastodon: siMastodon,
  bereal: siBereal,
  // Music / Podcasts
  deezer: siDeezer,
  tidal: siTidal,
  soundcloud: siSoundcloud,
  pocketcasts: siPocketcasts,
  overcast: siOvercast,
  castro: siCastro,
  // Gaming
  playstation: siPlaystation,
  playstationplus: siPlaystation,
  psplus: siPlaystation,
  psnow: siPlaystation,
  // Commerce
  shopify: siShopify,
  stripe: siStripe,
  // VPN / Security
  nordvpn: siNordvpn,
  expressvpn: siExpressvpn,
  proton: siProton,
  protonvpn: siProtonvpn,
  protonmail: siProtonmail,
  protonmailplus: siProtonmail,
  protonpass: siProton,
  protondrive: siProtondrive,
  // Passwords
  "1password": si1password,
  onepassword: si1password,
  lastpass: siLastpass,
  bitwarden: siBitwarden,
  dashlane: siDashlane,
  // Reading / News
  audible: siAudible,
  newyorktimes: siNewyorktimes,
  nyt: siNewyorktimes,
  // Fitness / Wellness
  peloton: siPeloton,
  headspace: siHeadspace,
  // Other
  duolingo: siDuolingo,
};

export function getServiceIcon(name: string): IconData | null {
  return ICON_MAP[normalize(name)] ?? null;
}

/** Returns true if the hex color is light (needs a dark icon/text on top) */
export function isLightHex(hex: string): boolean {
  const r = parseInt(hex.slice(0, 2), 16);
  const g = parseInt(hex.slice(2, 4), 16);
  const b = parseInt(hex.slice(4, 6), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 > 160;
}
